TidesofV =  {
    ["DefaultCover"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/DefaultCover",

    [1] = {  ["Title"] = "The Black Light", --Xal'atath 128827√
             ["Description"] = "Read the story of Xal'atath.",
             ["Icon"] = 1129654,
             ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Xalatath",
             ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Xalatath",
             ["Location"] = "<?? ??> Xal, Realm Unknown",
             ["Lore"] = "The origin of Xal'atath, Blade of the Black Empire remains uncertain. Some say it was created from the power of Y'Shaarj, others believe the blade itself is a forgotten Old God. But one thing is for sure, Xal'atath is truly ancient and it has a mind of its own.\n\nOver the years there have been many attempts to harness its power, but almost without exception, the Blade used its wielders to achieve its own agenda. Its last appearance was in the third invasion of the Burning Legion. The blade was retaken by an outstanding priest and was used as a powerful weapon against the Legion. Rumor has it that the Blade is in a dormant state and has probably gone missing since then.",
             ["x1"] = 0,
             ["y1"] = 0,
             ["x2"] = 0,
             ["y2"] = 0,
             ["mapID"] = 0,
             ["Status"] = true},

    [2] = {  ["Title"] = "Waning Crescent", --Sira Moonwarden √
             ["Description"] = "Meet Sira Moonwarden on the Isle of the Watchers.",
             ["Icon"] = 1033491,
	     ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/SiraMoonwarden",
	     ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/SiraMoonwarden-faded",
             ["Location"] = "<47.8 72.5> Isle of the Watchers, Azsuna",
             ["Lore"] = "Several years ago, you met Sira Moonwarden at the Molten Front in the Firelands. She was one of the Shadow Wardens that fought along with you against Ragnaros' forces and Fandral Staghelm. Years later, she went to alternate Draenor to bodyguard Archmage Khadgar (as if he would need any extra protection)\n\nYour paths crossed again during the Burning Legion's third invasion. She became the acting leader of the Wardens while Maiev was missing. Sira was stationed on the Isle of the Watchers where she randomly distributed her spare cloaks to esteemed allies of the Wardens.\n\nNow, after the Burning of Teldrassil, Sira Moonwarden and her people swear to retake the Darkshore. There, they will fight until their last breath...",
             ["x1"] = 0.4776,
             ["y1"] = 0.7224,
             ["x2"] = 0.4796,
             ["y2"] = 0.7272,
             ["mapID"] = 630,
             ["npcID"] = {102055},
             ["Status"] = false},
             
    [3] = {  ["Title"] = "A Jastor Prepares", --Jastor Gallywix √
             ["Description"] = "Behold the giant statue of Gallywix.",
             ["Icon"] = 1712097,
	     ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Gallywix",
	     ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Gallywix-faded",
             ["Location"] = "<27.2 53.5> West to the Gallywix Pleasure Palace, Azshara",
             ["Lore"] = "Jastor Gallywix was not born with a silver spoon in his mouth. Before he became the Trade Prince of the Bilgewater Cartel, he was merely the son of a regular tinker who owned a shop in the bad part of the Drudgetown slums and his mother left them for a life of piracy. As Gallywix turned ten, he witnessed a local gang rough up his father for money and steal a rare cookie his father had given him. This incident inspired him to take over the family tinkering business and the local crime syndicate. He blew the entire gang sky-high with booby-trapped bomb.\n\nYears later, Gallywix became the President of the massive Copper Street Conglomerate. And he eventually bought out Maldy’s entire companies and replaced him as the new Trade Prince of the Bilgewater Cartel. Gallywix exiled Maldy and his daughter, and later arranged Maldy’s accidental death. He did spare Madly’s daughter, Nessa’s life, for she is the one Gallywix fell in love with. But apparently this affection is no way mutual.\n\nIf you saw him taking things such as royal treasures from his allies. Don’t be surprised.",
             ["x1"] = 0.2482,
             ["y1"] = 0.5100,
             ["x2"] = 0.2875,
             ["y2"] = 0.5830,
             ["mapID"] = 76,
             ["Status"] = false},

    [4] = {  ["Title"] = "Cogito, Ergo Sum", --Grong gorilla√
             ["Description"] = "Investigate what has happened in Gorilla Gorge.",
             ["Icon"] = 2484332,
             ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Grong",
             ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Grong-faded",
             ["Location"] = "<47.2 51.6> Gorilla Gorge, Zuldazar",
             ["Lore"] = "In the ancient times, Keeper Mimiron discovered kaja'mite and noticed it had the ability to enchance some races' intellect. The keeper tested this mineral on a small, primitive race roamed the forestlands near Ulduar. Kaja'mite transformed the creatures into a highly intelligent, industrious breed known thereafter as goblins.\n\nSimilarly, due to the exposure to Kaja'mite, the gorillas here have developed self-awareness. With great intelligence comes great conflict. Their society split into two groups. The peace-loving Da'kani were imprisoned by their brethren. With the help of adventurers, King Da'ka was taken down. Although the reign of violence has ended, the Da'kani will stop at nothing to fight for their freedom.",
             ["x1"] = 0.4645,
             ["y1"] = 0.5120,
             ["x2"] = 0.4750,
             ["y2"] = 0.5182,
             ["mapID"] = 862,
             ["Status"] = false},

    [5] = { ["Title"] = "King of Gnomes", --Mekkatorque √
             ["Description"] = "Find Mekkatorque at Stormwind Embassy.",
             ["Icon"] = 2484337,
	     ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Mekkatorque",
	     ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Mekkatorque-faded",
             ["Location"] = "<52.4 14.3> Stormwind Embassy, Stormwind City",
             ["Lore"] = "Gelbin Mekkatorque is the current High Tinker of Gnomeregan, the elected leader of the gnomes and the Chief Finish Judge of the Great Gnomeregan Run. But most of all, he is a brilliant inventor.\n\nHe invented Mechanostrider and designed the wondrous Deeprun Tram running from Ironforge to Stormwind City. His gadgets has helped the Alliance countless times. During the Legion's invasion of the Broken Shore, Mekkatorque fought along with his allies on his new steam armor. The state-of-the-art armor was once again proved helpful during the battle for Lordaeron. He will use his bravery and creativity to crush the enemies of the Alliance.",
             ["x1"] = 0.5011,
             ["y1"] = 0.1069,
             ["x2"] = 0.5513,
             ["y2"] = 0.1631,
             ["mapID"] = 84,
             ["npcID"] = {126326},
             ["Status"] = false},

    [6] = { ["Title"] = "Sanitation Failure", --Gnomeregan √
             ["Description"] = "Take an elevator to enter Gnomeregan.",
             ["Icon"] = 255129,
	     ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Gnomeregan",
	     ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Gnomeregan-faded",
             ["Location"] = "<32.8 37.1> Gnomeregan, New Tinkertown, Dun Morogh",
             ["Lore"] = "With the knowledge of stoneworking and construction taught by their dwarven ally, the gnomes built their wondrous city--Gnomeregan. \n\nMore than two thousand years later, its impenetrable gate protected the city from orcs during the the Second War. However, when an overwhelming number of troggs emerged from the earth, they had to evacuate to the surface.\n\nTo eliminate the troggs, Mekkatorque agreed to the plan proposed by his entrusted advisor Sicco Thermaplugg, which involved bathing the city in radiation. What the High Tinker did not know back then was his advisor had plotted against him. The radiation cannot kill troggs as  Thermaplugg had claimed. It made the troggs even more agitated and turned some of the gnomes into leper gnomes. Thermaplugg created this tragedy so people would blame Mekkatorque and choose him instead as their new leader.\n\nAlthough Thermaplugg's plan did not work. The lower levels of Gnomeregan is still uninhabitable.",
             ["x1"] = -1,
             ["y1"] = -1,
             ["x2"] = 1,
             ["y2"] = 1,
             ["mapID"] = 30,
             ["Status"] = false},
             
    [7] = { ["Title"] = "Pride of the Sunstriders", --Anasterian Sunstrider √
             ["Description"] = "Read the plaque at the Shrine of Dath'Remar.",
             ["Icon"] = 1119643,
	     ["Image"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Anasterian",
	     ["Image-faded"] = "Interface/AddOns/AzerothAdventureAlbum/ART/Album/3/Anasterian-faded",
             ["Location"] = "<35.5 40.2> Sunstrider Isle, Eversong Woods",
             ["Lore"] = "In a moon-worshipping culture, the name \"Sunstrider\" seems a bit heterodox. Their progenitors chose this name to symbolize their penchant for delving into the unknown, for breaking expectations and choosing greatness over cautions. For generations the Sunstriders carried on this tradition with pride.\n\nAfter the Great Sundering, Dath'Remar Sunstrider, the great grandfather of Anasterian and the great-great grandfather of Kael'thas, believed that night elf society could rebuilt their mighty empire. To do so, Dath'Remar and his followers revived the study and use of arcane power, a power which draw the Legion to Azeroth. And because of such defiance, they were exiled, cut off from the Well of Eternity's energies.\n\nDath'Remar and his followers sailed across the sea and discovered a new continent, later known as the Eastern Kingdoms, and they eventually reach the nexus of ley lines in the north. There Dath'Remar used a stole vial filled with the waters from the original Well of Eternity to create a new power source for his people. They dubbed it the Sunwell in honor of Dath'Remar and believed he had brought them salvation. They called their new land Quel'Thalas and the traditional worship of the moon was gradually abandoned.",
             ["x1"] = 0.3467,
             ["y1"] = 0.3886,
             ["x2"] = 0.3603,
             ["y2"] = 0.4100,
             ["mapID"] = 467,
             ["npcID"] = 0,
             ["GossipOption"] = 0,
             ["Status"] = false},
}
